export const CREATE_NEW_PROJECT_REQUEST = 'CREATE_NEW_PROJECT_REQUEST';
export const CREATE_NEW_PROJECT_SUCCESS = 'CREATE_NEW_PROJECT_SUCCESS';
export const CREATE_NEW_PROJECT_FAIL = 'CREATE_NEW_PROJECT_FAIL';
export const CREATE_NEW_PROJECT_RESET = 'CREATE_NEW_PROJECT_RESET';
