export const CREATE_NEW_PROJECT_REQUEST = 'CREATE_NEW_PROJECT_REQUEST';
export const CREATE_NEW_PROJECT_SUCCESS = 'CREATE_NEW_PROJECT_SUCCESS';
export const CREATE_NEW_PROJECT_FAIL = 'CREATE_NEW_PROJECT_FAIL';
export const CREATE_NEW_PROJECT_RESET = 'CREATE_NEW_PROJECT_RESET';

export const GET_PROJECTS_REQUEST = 'GET_PROJECTS_REQUEST';
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS';
export const GET_PROJECTS_FAIL = 'GET_PROJECTS_FAIL';

export const GET_PROJECT_BY_ID_REQUEST = 'GET_PROJECT_BY_ID_REQUEST';
export const GET_PROJECT_BY_ID_SUCCESS = 'GET_PROJECT_BY_ID_SUCCESS';
export const GET_PROJECT_BY_ID_FAIL = 'GET_PROJECT_BY_ID_FAIL';
export const GET_PROJECT_BY_ID_RESET = 'GET_PROJECT_BY_ID_RESET';

export const DELETE_PROJECT_REQUEST = 'DELETE_PROJECT_REQUEST';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAIL = 'DELETE_PROJECT_FAIL';

export const GET_PROJECT_BACKLOG_REQUEST = 'GET_PROJECT_BACKLOG_REQUEST';
export const GET_PROJECT_BACKLOG_SUCCESS = 'GET_PROJECT_BACKLOG_SUCCESS';
export const GET_PROJECT_BACKLOG_FAIL = 'GET_PROJECT_BACKLOG_FAIL';

export const GET_PROJECT_TASK_REQUEST = 'GET_PROJECT_TASK_REQUEST';
export const GET_PROJECT_TASK_SUCCESS = 'GET_PROJECT_TASK_SUCCESS';
export const GET_PROJECT_TASK_FAIL = 'GET_PROJECT_TASK_FAIL';

export const DELETE_PROJECT_TASK_REQUEST = 'DELETE_PROJECT_TASK_REQUEST';
export const DELETE_PROJECT_TASK_SUCCESS = 'DELETE_PROJECT_TASK_SUCCESS';
export const DELETE_PROJECT_TASK_FAIL = 'DELETE_PROJECT_TASK_FAIL';

export const ADD_PROJECT_TASK_REQUEST = 'ADD_PROJECT_TASK_REQUEST';
export const ADD_PROJECT_TASK_SUCCESS = 'ADD_PROJECT_TASK_SUCCESS';
export const ADD_PROJECT_TASK_FAIL = 'ADD_PROJECT_TASK_FAIL';
export const ADD_PROJECT_TASK_RESET = 'ADD_PROJECT_TASK_RESET';
